# Generated by Django 3.2.9 on 2021-11-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Text_To_Speech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_in_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname_register', models.CharField(max_length=20)),
                ('email_register', models.EmailField(max_length=50)),
                ('pword_register', models.IntegerField()),
                ('pwordconform', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sign_in_Data',
        ),
    ]
