# Generated by Django 3.2.9 on 2021-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Text_To_Speech', '0002_auto_20211107_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_in_data',
            name='pword_register',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='register_in_data',
            name='pwordconform',
            field=models.CharField(max_length=18),
        ),
    ]
